name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image to run unit tests
      run: docker build . --file Dockerfile --no-cache --tag team2470/2021-robotLibraries:$(date +%s)
